### ISSUE TITLE
Названия счётчиков

### ISSUE THREAD

**Issue by Dan1LExtr1m** [denys00/alchdev#1]
Нужно ли добавить возможность делать пробелы в названиях счётчиках в версии 0.5.2?

**Comment by denys00** [comment]
Это будет сделано в обновлении _0.6_

**Comment by Dan1LExtr1m** [comment]
По сути это "баг", так что это можно исправить в багфиксе 0.5.2.

**Comment by denys00** [comment]
Это уже написано в ТЗ обновления _0.6_
